import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='flex h-full flex-col justify-center items-center'>
          <h1 className='text-4xl mb-5 font-bold'>Home</h1>
          <span className='text-7xl'>🏡</span>
        </div>
      </main>
    </>
  )
}
